name: studysync
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_nearby_connections: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.5.1
  dio: ^5.3.3
  jwt_decode: ^0.3.1
  supabase_flutter: 2.9.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  shared_preferences: ^2.2.2
  sensors_plus: ^6.1.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  app_links: ^3.5.1
  sign_in_with_apple: ^7.0.1
  provider: ^6.0.5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

dependency_overrides:
  geolocator_android: ^5.0.1

flutter:
  uses-material-design: true